### tested
POST http://localhost:8080/recipes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjU0Mzg0MzkxfQ.gGVYD7rjvXDb1_bsyeCZCVA6oFWsQ3yz38wC2ne0S4k

{
    "name": "Homemade Pizza",
    "tags" : ["italian", "pizza", "dinner"],
    "ingredients": [
        "pizza dough",
        "tomato sauce",
        "olive oil",
        "7 ounces fresh mozzarella cheese, cut into 1/2-inch cubes",
        "5 - 6 large fresh basil leaves"
    ],
    "instructions": []
}

### tested
GET http://localhost:8080/recipes/629be55fc8dc0af8e5a64ee8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjU0Mzg0MzkxfQ.gGVYD7rjvXDb1_bsyeCZCVA6oFWsQ3yz38wC2ne0S4k

### tested
PUT http://localhost:8080/recipes/629652ceae2b50bda3e874d3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjU0Mzg0MzkxfQ.gGVYD7rjvXDb1_bsyeCZCVA6oFWsQ3yz38wC2ne0S4k

{
    "name": "Pepperoni Pizza",
    "tags" : ["italian", "pizza", "dinner"],
    "ingredients": [
        "pizza dough",
        "tomato sauce",
        "olive oil",
        "7 ounces fresh mozzarella cheese, cut into 1/2-inch cubes",
        "5 - 6 large fresh basil leaves"
    ],
    "instructions": []
}

### search recipes by tag [DEPRECATED]
GET http://localhost:8080/recipes/search?tag=italian

### tested
DELETE http://localhost:8080/recipes/629652ceae2b50bda3e874d3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjU0Mzg0MzkxfQ.gGVYD7rjvXDb1_bsyeCZCVA6oFWsQ3yz38wC2ne0S4k
