POST http://localhost:8080/recipes
Content-Type: application/json

{
    "name": "Homemade Pizza",
    "tags" : ["italian", "pizza", "dinner"],
    "ingredients": [
        "pizza dough",
        "tomato sauce",
        "olive oil",
        "7 ounces fresh mozzarella cheese, cut into 1/2-inch cubes",
        "5 - 6 large fresh basil leaves"
    ],
    "instructions": []
}

###

GET http://localhost:8080/recipes


###

PUT http://localhost:8080/recipes/caal1b06f2qcktvbb1bg
Content-Type: application/json

{
    "name": "Pepperoni Pizza",
    "tags" : ["italian", "pizza", "dinner"],
    "ingredients": [
        "pizza dough",
        "tomato sauce",
        "olive oil",
        "7 ounces fresh mozzarella cheese, cut into 1/2-inch cubes",
        "5 - 6 large fresh basil leaves"
    ],
    "instructions": []
}

### search recipes by tag
GET http://localhost:8080/recipes/search?tag=italian
